version: "3.8"

services:
  ts-syncthing:
    image: tailscale/tailscale:v1.98.4
    container_name: ts-syncthing
    hostname: syncthing
    secrets:
      - ts_authkey
    environment:
      - TS_AUTHKEY_FILE=/run/secrets/ts_authkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    volumes:
      - tailscale-data-syncthing:/var/lib/tailscale
      - ${INFRA_ROOT}/nas/syncthing/ts-syncthing-config:/config
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  syncthing:
    image: ghcr.io/vaskozl/syncthing:2.1.0@sha256:530f493e0397284db14f2731d54dbb1efc33ce6c42dc4420496929e95add7f9c
    container_name: syncthing
    restart: unless-stopped
    network_mode: service:ts-syncthing
    depends_on:
      - ts-syncthing
    user: "568:568"
    environment:
      - HOME=/var/syncthing
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ${INFRA_ROOT}/nas/syncthing/data:/var/syncthing
      - /mnt/Pool/sync-bucket:/incoming
      - /mnt/Pool/Syncthing/vw:/sync/vw

volumes:
  tailscale-data-syncthing:

secrets:
  ts_authkey:
    file: ../../secrets/ts-authkey.enc.txt
