version: "3.9"

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.108.0
    container_name: doco-cd
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./doco-cd-data:/data       # persistent logs/cache
      - /var/run/docker.sock:/var/run/docker.sock  # needed for docker-compose deploys
    ports:
      - "9080:80"  # optional health/metrics endpoint
    environment:
      PASS_ENV: "true"
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      GIT_ACCESS_TOKEN_FILE: /run/secrets/doco-git-token
      TZ: Europe/Stockholm
      POLL_CONFIG: |
        - url: https://github.com/kekizl/home-infra.git
          reference: main
          interval: 1800
          target: ${DOCO_CD_TARGET}
    secrets:
      - sops_age_key
      - doco-git-token
    dns:
      - 8.8.8.8 # to avoid circular dependency with AdguardHome
    labels:
      - "docker-volume-backup.stop-during-backup=true"

networks:
  proxy:
    driver: bridge

volumes:
  data:

secrets:
  sops_age_key:
    file: ../.config/sops/age/sops_age_key.txt
  doco-git-token:
    file: secrets/doco-git-token.enc.txt
