INTENTS = {
    "chat": [
        "who was napoleon",
        "what is the capital of france",
        "tell me a joke",
        "what is the meaning of life",
        "how does photosynthesis work",
        "how tall is mount everest",
        "what year was the eiffel tower built",
        "who was george washington",
        "who was joseph stalin",
        "what caused world war two",
        "how far away is the moon",
        "what is the speed of light",
        "why is the sky blue",
        "who invented the telephone",
        "what is the largest country in the world",
        "how many bones are in the human body",
        "what is quantum physics",
        "tell me something interesting",
        "what is the population of china",
        "how do black holes form",
    ],
    "code": [
        "write a python function to sort a list",
        "what is the difference between a list and a tuple",
        "how do I reverse a string in javascript",
        "explain what a pointer is in c++",
        "what size is an int in c++",
        "how does async await work",
        "write a sql query to get all users",
        "what is a race condition",
        "how do I use a dictionary in python",
        "what is object oriented programming",
        "explain recursion with an example",
        "what is the difference between tcp and udp",
        "how does garbage collection work",
        "write a function to check if a number is prime",
        "what is big o notation",
        "how do I handle errors in rust",
        "what is a binary search tree",
        "explain the difference between stack and heap",
        "how do I center a div in css",
        "what is a rest api",
    ],
    "personal": [
        "what do I have on my calendar today",
        "what are my notes about the project",
        "what did I do last tuesday",
        "show me my tasks for this week",
        "what did I write about the meeting",
        "do I have any appointments tomorrow",
        "what was the name of that restaurant I liked",
        "what are my goals for this month",
        "what did I note about the doctor visit",
        "remind me what I said about the trip",
    ],
    "medicine": [
        "what are the symptoms of a common cold",
        "how is high blood pressure treated",
        "what is the difference between a virus and bacteria",
        "what does an MRI scan show",
        "how do antibiotics work",
        "what should I do if I have chest pain",
        "what are the side effects of ibuprofen",
        "how is diabetes diagnosed",
        "what is the normal range for blood pressure",
        "explain what a stroke is",
        "what vaccines are recommended for adults",
        "how does the immune system fight infection",
        "what is the recovery time for a broken leg",
        "what are the signs of dehydration",
        "how often should I get a physical exam",
        "what is the difference between a sprain and a strain",
        "how does chemotherapy treat cancer",
        "what causes migraines",
        "what is the first aid for a burn",
        "what does a cardiologist do",
    ],
    "law": [
        "what is the difference between civil and criminal law",
        "how do I file a small claims lawsuit",
        "what is a contract and what makes it legally binding",
        "what are my rights if I am arrested",
        "explain what a tort is in simple terms",
        "what is the statute of limitations for fraud",
        "how does child custody work in divorce",
        "what is the difference between a will and a trust",
        "what does intellectual property law cover",
        "how do I evict a tenant legally",
        "what is the definition of defamation",
        "what are the steps in a typical criminal trial",
        "what is the role of a judge versus a jury",
        "how is negligence determined in a lawsuit",
        "what is the difference between a felony and a misdemeanor",
        "what does 'beyond a reasonable doubt' mean",
        "how do I trademark a business name",
        "what is the legal drinking age and why",
        "what are the penalties for copyright infringement",
        "explain what a power of attorney does",
    ],
}
