INTENTS = {
    "home": [
        "turn on the lights",
        "turn off the kitchen light",
        "set the thermostat to 22 degrees",
        "lock the front door",
        "what is the temperature inside",
        "is the garage door open",
        "switch off all lights",
        "dim the bedroom lights",
        "turn on the fan",
        "what devices are on",
        "add milk to my shopping list",
        "add eggs to my shopping list",
        "remove item from shopping list",
        "what is on my shopping list",
        "check the shopping list",
        "turn off the tv",
        "set an alarm for 7am",
        "what lights are on",
        "close the blinds",
        "turn on the heating",
    ],
    "chat": [
        "who was napoleon",
        "what is the capital of france",
        "tell me a joke",
        "what is the meaning of life",
        "how does photosynthesis work",
        "how tall is mount everest",
        "what year was the eiffel tower built",
        "who was george washington",
        "who was joseph stalin",
        "what caused world war two",
        "how far away is the moon",
        "what is the speed of light",
        "why is the sky blue",
        "who invented the telephone",
        "what is the largest country in the world",
        "how many bones are in the human body",
        "what is quantum physics",
        "tell me something interesting",
        "what is the population of china",
        "how do black holes form",
    ],
    "code": [
        "write a python function to sort a list",
        "what is the difference between a list and a tuple",
        "how do I reverse a string in javascript",
        "explain what a pointer is in c++",
        "what size is an int in c++",
        "how does async await work",
        "write a sql query to get all users",
        "what is a race condition",
        "how do I use a dictionary in python",
        "what is object oriented programming",
        "explain recursion with an example",
        "what is the difference between tcp and udp",
        "how does garbage collection work",
        "write a function to check if a number is prime",
        "what is big o notation",
        "how do I handle errors in rust",
        "what is a binary search tree",
        "explain the difference between stack and heap",
        "how do I center a div in css",
        "what is a rest api",
    ],
    "personal": [
        "what do I have on my calendar today",
        "what are my notes about the project",
        "what did I do last tuesday",
        "show me my tasks for this week",
        "what did I write about the meeting",
        "do I have any appointments tomorrow",
        "what was the name of that restaurant I liked",
        "what are my goals for this month",
        "what did I note about the doctor visit",
        "remind me what I said about the trip",
    ],
}
