commands:
    dry_run: false
    cross_seed: false
    recheck: false
    cat_update: false
    tag_update: false
    rem_unregistered: true
    tag_tracker_error: false
    rem_orphaned: true
    tag_nohardlinks: true
    share_limits: true
    skip_cleanup: false
    skip_qb_version_check: false
qbt:
    host: ENC[AES256_GCM,data:poCln926OIwjU/G6FmXDF7hwSR0=,iv:s2L1/URcp9EN8Vis905+qBD3zry0NTb1Gvb2/xjAnog=,tag:MAZeMI88JOuZOxNXNvb7PA==,type:str]
    user: ENC[AES256_GCM,data:6jNupO4=,iv:SvoGZMGDJxEbM0Jv7wIXiHb/Ae1PnlPvzrDxHvG9j5w=,tag:JgLMmH29/EW6GK1mPmAd4g==,type:str]
    pass: ENC[AES256_GCM,data:dwoRnWkNIOZUAi9DAud57g==,iv:RRLnVIJdfDUuapan47C+m1a+ajz0k1l88fhYokxmgHE=,tag:8VdSJhMy9tJBCTcERElKpg==,type:str]
settings:
    force_auto_tmm: false
    tracker_error_tag: issue
    nohardlinks_tag: noHL
    share_limits_suffix_tag: share_limit
    ignoreTags_OnUpdate:
        - noHL
        - issue
        - cross-seed
directory:
    root_dir: /downloads/
    remote_dir: /mnt/Pool/downloads/
    orphaned_dir: /downloads/orphaned_data
    recycle_bin: /downloads/.RecycleBin
    cross_seed: null
    torrents_dir: null
cat:
    lidarr: /downloads
tracker:
    passthepopcorn:
        tag: ENC[AES256_GCM,data:912/,iv:ib4di5Jxqk+B9WlVKlIxzS5t6bYy5r1Djkn48CxlD/A=,tag:QrKxzKfikeuatGmsvkdXtA==,type:str]
    torrentleech:
        tag: TorrentLeech
    other:
        tag: other
nohardlinks:
    - lidarr
share_limits:
    noHL:
        priority: 1
        include_all_tags:
            - noHL
        categories:
            - lidarr
        max_seeding_time: 360
        cleanup: true
recyclebin:
    enabled: true
    empty_after_x_days: 14
    save_torrents: false
    split_by_category: false
webhooks:
    error: null
    run_start: null
    run_end: null
    function:
        cross_seed: null
        recheck: null
        cat_update: null
        tag_update: null
        rem_unregistered: null
        tag_tracker_error: null
        rem_orphaned: null
        tag_nohardlinks: null
        cleanup_dirs: null
orphaned:
    empty_after_x_days: 2
    exclude_patterns: null
    max_orphaned_files_to_delete: 500
sops:
    age:
        - recipient: age10sgtrf8euyn5ph0qvvuy8vfvu9fs45d4e3yxheg0h2pdfluvns9s8a2qut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSTJhMEhJUjNnQTJvM3N5
            aTBrV2F4d1NNcjJWUlVUazUzT1VMc05GVjBrCjBQaE9aeVRHWDBWajc1YnFycit2
            WXZKVGdMWG9pb3MzV1FXUFZ3cFFjelEKLS0tIHlPZXJLWnd1Vng1NjlzSWJRMFpy
            TWNjWUxiUlUyNE9rTjJ1ZXJqU3c3Z2MKNPmLJR52W139NBAjDuPVXl8ZIRcFbG/3
            GOCr86Nq+1MIsvF5WTNuk8ZKrazzkXlO2KPwvhNgLT7NFwKhyJ/Duw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T23:51:32Z"
    mac: ENC[AES256_GCM,data:kGV/5zx/0v1DkSQVzO/ZJFAIAEuZ1dUHfcxx2ac8XBmhfbG9nLbUC4d/4SB/eAO1rEhwEu+bZCeTtaCsjTF2O3d4whxZh6iRsDBb9PYKgn9DPFvosSgecNiVhvDnH9T/T29LMMmhwRZmBQzCWfEnMXcksrJo5UQgKYXrZBnveSs=,iv:XhMj8ghlQ5NnhUK/Uh9wKlyWt14D6Xi6EI8h/Pq47Lg=,tag:XBm7RebgL3Mmg8o1XqVGaA==,type:str]
    encrypted_regex: (pass|user|host)
    version: 3.12.2
