commands:
    dry_run: false
    cross_seed: false
    recheck: false
    cat_update: false
    tag_update: false
    rem_unregistered: true
    tag_tracker_error: false
    rem_orphaned: true
    tag_nohardlinks: true
    share_limits: true
    skip_cleanup: false
    skip_qb_version_check: false
qbt:
    host: ENC[AES256_GCM,data:9dwKX15QQaJIXrfNipIKeypNc5BS6mmQ++bD,iv:wpmQ75cyiYsWxzo8N6QsUUHlkkIkGJY8gnv21dhYCzY=,tag:UKK8NHpNbNhqQsPvgNaxPg==,type:str]
    user: ENC[AES256_GCM,data:6jNupO4=,iv:SvoGZMGDJxEbM0Jv7wIXiHb/Ae1PnlPvzrDxHvG9j5w=,tag:JgLMmH29/EW6GK1mPmAd4g==,type:str]
    pass: ENC[AES256_GCM,data:dwoRnWkNIOZUAi9DAud57g==,iv:RRLnVIJdfDUuapan47C+m1a+ajz0k1l88fhYokxmgHE=,tag:8VdSJhMy9tJBCTcERElKpg==,type:str]
settings:
    force_auto_tmm: false
    tracker_error_tag: issue
    nohardlinks_tag: noHL
    share_limits_suffix_tag: share_limit
    ignoreTags_OnUpdate:
        - noHL
        - issue
        - cross-seed
directory:
    root_dir: /downloads/
    remote_dir: /mnt/Pool/downloads/
    orphaned_dir: /downloads/orphaned_data
    recycle_bin: /downloads/.RecycleBin
    cross_seed: null
    torrents_dir: null
cat:
    lidarr: /downloads
tracker:
    passthepopcorn:
        tag: ENC[AES256_GCM,data:912/,iv:ib4di5Jxqk+B9WlVKlIxzS5t6bYy5r1Djkn48CxlD/A=,tag:QrKxzKfikeuatGmsvkdXtA==,type:str]
    torrentleech:
        tag: TorrentLeech
    other:
        tag: other
nohardlinks:
    - lidarr
share_limits:
    noHL:
        priority: 1
        include_all_tags:
            - noHL
        categories:
            - lidarr
        max_seeding_time: 360
        cleanup: true
recyclebin:
    enabled: true
    empty_after_x_days: 14
    save_torrents: false
    split_by_category: false
webhooks:
    error: null
    run_start: null
    run_end: null
    function:
        cross_seed: null
        recheck: null
        cat_update: null
        tag_update: null
        rem_unregistered: null
        tag_tracker_error: null
        rem_orphaned: null
        tag_nohardlinks: null
        cleanup_dirs: null
orphaned:
    empty_after_x_days: 2
    exclude_patterns: null
    max_orphaned_files_to_delete: 500
sops:
    age:
        - recipient: age10sgtrf8euyn5ph0qvvuy8vfvu9fs45d4e3yxheg0h2pdfluvns9s8a2qut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSTJhMEhJUjNnQTJvM3N5
            aTBrV2F4d1NNcjJWUlVUazUzT1VMc05GVjBrCjBQaE9aeVRHWDBWajc1YnFycit2
            WXZKVGdMWG9pb3MzV1FXUFZ3cFFjelEKLS0tIHlPZXJLWnd1Vng1NjlzSWJRMFpy
            TWNjWUxiUlUyNE9rTjJ1ZXJqU3c3Z2MKNPmLJR52W139NBAjDuPVXl8ZIRcFbG/3
            GOCr86Nq+1MIsvF5WTNuk8ZKrazzkXlO2KPwvhNgLT7NFwKhyJ/Duw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T18:08:01Z"
    mac: ENC[AES256_GCM,data:XV/vFGyzBdsGp8QqR6cenfmKrcgIfWHDhYqW6eBQPyXxw+Cj0M7s0OLVVzHvUOHYcCkU8AyMTRSBgyr03fp6+Iipbq4YxQhip0vuy95di1XVtk3F+koNIXg9VlN2ScEApPRURBdSEeyNwQ6wwnarkhC7i9BYkh06eZDg+z65uqA=,iv:xRaSUSS97xIFmfhbmnV9tij/1oq7c+DA7eGCj/WxP2I=,tag:Q1aquOlT8gn9eaH05EJXSg==,type:str]
    encrypted_regex: (pass|user|host)
    version: 3.12.2
