version: "3.9"

services:
  ts-adguard:
    image: tailscale/tailscale:v1.96.5
    container_name: ts-adguard
    hostname: adguard
    secrets:
      - ts_authkey
    environment:
      - TS_AUTHKEY_FILE=/run/secrets/ts_authkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json   # optional, enables HTTPS
      - TS_USERSPACE=true
    volumes:
      - tailscale-data-adguard:/var/lib/tailscale
      - ${INFRA_ROOT}/mac-mini/dns/ts-adguard-config:/config          # mount folder for serve.json
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  adguard-home:
    image: adguard/adguardhome:v0.107.74
    container_name: adguardhome
    restart: unless-stopped
    network_mode: service:ts-adguard
    depends_on:
      - ts-adguard 
    volumes:
      - ${INFRA_ROOT}/mac-mini/dns/adguard/work:/opt/adguardhome/work
      - ${INFRA_ROOT}/mac-mini/dns/adguard/conf:/opt/adguardhome/conf
volumes:
  tailscale-data-adguard:

secrets:
  ts_authkey:
    file: ../../secrets/ts-authkey.enc.txt
